---
# run info
n_episodes: 50
seed: 42
n_workers: 2
max_optimisation_steps: 1000

# Learner Config
learner_config: 
    run_name: "FNN_run10"
    max_steps: 10000
    max_steps_per_episode: 400
    target_updates: 1000
    samples_per_update: 512
    batch_size: 256
    IS: true
    log_interval: 10
    n_workers: 6
    optimiser_config:
      type: "adam"
      learning_rate: 3e-4
    

# Controller Config
controller_config: 
    action_size: 5
    gae_horizon: 16
    n_epochs_update: 3
    gamma: 0.995
    lam: 0.95
    clip_epsilon: 0.2
    value_loss_coefficient: 0.5
    entropy_coefficient: 0.01
    tau: 0.99
    n_features: 12
    actor_config:
      type: "FNN"
      layer_sizes: 
      - 512
      - 256
      - 128
    critic_config:
      type: "FNN"
      layer_sizes: 
      - 256
      - 128


# Environment Config
environment_config:
    scenario_name: "simple_avoidance"
    observation_builder_config: 
      type: "tree"
      predictor: "shortest_path"
      max_depth: 3